site_name: 基石库
site_author: ricolxwz
site_url: https://gk.ricolxwz.de/
# repo_url: https://github.com/ricolxwz/gk
edit_uri: https://github.com/ricolxwz/gk/edit/master/docs
copyright: <p xmlns:cc="http://creativecommons.org/ns#" >版权所有 &copy 2024-至今 由 <span property="cc:attributionName">许文泽</span> 采用 <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0&nbsp</a>许可证发布</p>
site_description: 一个基础知石仓库
theme:
  name: material
  logo_light_mode: https://cdn.jsdelivr.net/gh/sigmax0124/logo@master/favion-big-mc-212121-000000-1.svg 
  logo_dark_mode: https://cdn.jsdelivr.net/gh/sigmax0124/logo@master/favion-big-mc-000000-212121-1.svg
  language: zh
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips
    - content.tooltips
    - content.action.edit
    - content.action.view
    # - header.autohide
    # - announce.dismiss
    # - navigation.footer
    - navigation.tabs
    - navitation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
  icon:
    annotation: material/star-four-points-circle
    repo: fontawesome/brands/github
    # admonition:
    #   note: octicons/tag-16
    #   abstract: octicons/checklist-16
    #   info: octicons/info-16
    #   tip: octicons/squirrel-16
    #   success: octicons/check-16
    #   question: octicons/question-16
    #   warning: octicons/alert-16
    #   failure: octicons/x-circle-16
    #   danger: octicons/zap-16
    #   bug: octicons/bug-16
    #   example: octicons/beaker-16
    #   quote: octicons/quote-16 
extra:
  social:
    - icon: fontawesome/compass-solid
      link: https://ricolxwz.de
    - icon: fontawesome/brands/github
      link: https://github.com/ricolxwz
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/ricolxwz
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ricolxwz
    - icon: fontawesome/telegram-brands-solid
      link: https://t.me/ricolxwz
    - icon: fontawesome/at-solid
      link: mailto:ricol.xwz@outlook.com
  generator: false
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/favicon.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/analysis.js
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - i18n:
      enabled: !ENV [EN, CI, false]
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            事务: Transactions
  - search:
      separator: '[\s\u200b\-]'
  - open-in-new-tab
  - glightbox
  - git-revision-date-localized:
      locale: zh
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - git-committers:
      repository: ricolxwz/gk
      branch: master
      enabled: !ENV [CI, false]
nav:
  - 开始:
    - index.md
  - 数据库:
    - 绪论: database/index.md
    - 数据模型: database/conceptual-model.md
    - 关系模型: database/relational-model.md
    - 关系代数: database/relational-algebra.md
    - SQL: database/sql.md
    - 完整性约束: database/integrity-constraints.md
    - 高级SQL: database/advanced-sql.md
    - 应用开发: database/app-dev.md
    - 规范化: database/normalization.md
    - 事务: database/transaction.md
  - 信息论:
    - 绪论: information-theory/index.md
    - 不确定性和熵: information-theory/uncertainty-and-entropy.md
    - 什么是信息: information-theory/what-is-information.md
    - JIDT: information-theory/jidt.md
    - 估计器: information-theory/estimator.md
    - 统计显著性: information-theory/statistical-significance.md
    - 自组织: information-theory/self-organisation.md
    - 信息处理: information-theory/information-processing.md
    - 信息存储: information-theory/information-storage.md
    - 信息传递: information-theory/information-transfer.md
  - 版本控制:
    - 区域和状态: version-control/area-and-status.md
    - 添加和提交: version-control/add-and-commit.md
    - 回退: version-control/revert.md
    - 配置: version-control/config.md
    - 账户: version-control/account.md
  - 容器:
    - dockerfile: containerization/dockerfile.md
  - k8s:
    - 架构: k8s/architecture.md
    - 命令: k8s/command.md
    - 示例: k8s/example.md